# Generated by Django 4.1.7 on 2023-03-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group_name',
        ),
    ]
