# Generated by Django 4.1.7 on 2023-03-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_groupspending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupspending',
            name='total_spending',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
