# Generated by Django 4.1.7 on 2023-03-23 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_groupspending_total_spending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupspending',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spending', to='core.group'),
        ),
    ]
